# Generated by Django 4.0 on 2022-01-01 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='end',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 1, 22, 16, 44, 140181)),
        ),
        migrations.AddField(
            model_name='semester',
            name='start',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 1, 22, 16, 44, 140181)),
        ),
    ]
