# Generated by Django 4.0 on 2022-01-03 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unimanager', '0002_semester_end_semester_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprelation',
            name='subject',
        ),
        migrations.AlterField(
            model_name='semester',
            name='end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='start',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='sprelation',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='unimanager.professorsubject'),
        ),
        migrations.AlterField(
            model_name='sprelation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='unimanager.studentsubject'),
        ),
    ]
