# Generated by Django 4.0 on 2021-12-30 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unimanager', '0002_professorsubject_schoolyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='teacher_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unimanager.user'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unimanager.user'),
        ),
    ]
