# Generated by Django 4.0 on 2022-01-03 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unimanager', '0003_remove_sprelation_subject_alter_semester_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprelation',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='unimanager.subject'),
        ),
        migrations.AlterField(
            model_name='sprelation',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='unimanager.professor'),
        ),
        migrations.AlterField(
            model_name='sprelation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='unimanager.student'),
        ),
    ]
