# Generated by Django 4.0 on 2022-01-03 20:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unimanager', '0004_sprelation_subject_alter_sprelation_professor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprelation',
            name='subject',
        ),
        migrations.AlterField(
            model_name='sprelation',
            name='mark',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='sprelation',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='unimanager.professorsubject'),
        ),
        migrations.AlterField(
            model_name='sprelation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='unimanager.studentsubject'),
        ),
    ]
