# Generated by Django 4.0 on 2022-01-05 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimanager', '0005_remove_sprelation_subject_alter_sprelation_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprelation',
            name='mark',
            field=models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
    ]
